/* GENERATED by Selftest_pmu/gen_npu_pmu_regs.py -- do not edit.
 *
 * Extracted from the Ethos-U core driver's register map:
 *   /opt/arm/ml-embedded-evaluation-kit/dependencies/core-driver/src/ethosu85_interface.h
 *
 * The driver is NOT linked; only the register geometry is borrowed,
 * and check mode re-verifies it against the vendor header.
 *
 * EVERY cycle-counter bit below comes from ITS OWN register struct.
 * Deriving one from another is what produced the milestone-1 defect:
 * the cycle bit was computed as 1<<8 from the event-counter count,
 * but 8 event bits are followed by 23 reserved bits, so the real
 * position is 31. Bit 8 is reserved and reads as zero, which made a
 * wrapped counter look overflow-free.
 */
#ifndef NPU_PMU_REGS_H
#define NPU_PMU_REGS_H

/* Register offsets, relative to the NPU base (U85_BASE_ADDRESS). */
#define NPU_REG_PMCR                 0x1180U
#define NPU_REG_PMCNTENSET           0x1184U
#define NPU_REG_PMCNTENCLR           0x1188U
#define NPU_REG_PMOVSSET             0x118CU
#define NPU_REG_PMOVSCLR             0x1190U
#define NPU_REG_PMINTSET             0x1194U
#define NPU_REG_PMINTCLR             0x1198U
#define NPU_REG_PMCCNTR              0x11A0U
#define NPU_REG_PMCCNTR_HI           0x11A4U
#define NPU_REG_PMCCNTR_CFG          0x11A8U
#define NPU_REG_PMEVCNTR_BASE        0x1300U
#define NPU_REG_PMEVTYPER_BASE       0x1380U

#define NPU_PMU_EVENT_COUNTERS_MAX   8U
#define NPU_PMU_EVENT_COUNTER_WIDTH  32U

/* Cycle counter is 48 bits (LO 32 + HI 16), NOT 64. */
#define NPU_PMU_CYCLE_COUNTER_WIDTH  48U
#define NPU_PMU_CYCLE_HI_VALID_BITS  16U

#define NPU_PMCR_CNT_EN_POS 0U
#define NPU_PMCR_CNT_EN_MSK 0x00000001U
#define NPU_PMCR_EVENT_CNT_RST_POS 1U
#define NPU_PMCR_EVENT_CNT_RST_MSK 0x00000002U
#define NPU_PMCR_CYCLE_CNT_RST_POS 2U
#define NPU_PMCR_CYCLE_CNT_RST_MSK 0x00000004U
#define NPU_PMCR_MASK_EN_POS 3U
#define NPU_PMCR_MASK_EN_MSK 0x00000008U
#define NPU_PMCR_NUM_EVENT_CNT_POS 11U
#define NPU_PMCR_NUM_EVENT_CNT_MSK 0x0000F800U

/* Per-register cycle bits. Never derived from the counter count. */
#define NPU_PMU_PMCNTEN_CYCLE_SHIFT   31U
#define NPU_PMU_PMCNTEN_CYCLE_MASK    (1U << NPU_PMU_PMCNTEN_CYCLE_SHIFT)
#define NPU_PMU_PMOVS_CYCLE_OVF_SHIFT 31U
#define NPU_PMU_PMOVS_CYCLE_OVF_MASK  (1U << NPU_PMU_PMOVS_CYCLE_OVF_SHIFT)

/* Cycle-counter gating. The value is COMPOSED from the extracted
 * field positions and event numbers -- 0x11 is never written into
 * the source. It only appears in the static assertion below, as a
 * cross-check against the independently published encoding. */
#define NPU_PMU_PMCCNTR_CFG_START_SHIFT 0U
#define NPU_PMU_PMCCNTR_CFG_START_MASK  0x000003FFU
#define NPU_PMU_PMCCNTR_CFG_STOP_SHIFT  16U
#define NPU_PMU_PMCCNTR_CFG_STOP_MASK   0x03FF0000U
#define NPU_PMU_EVENT_CYCLE             17U
#define NPU_PMU_EVENT_NO_EVENT          0U
#define NPU_PMU_CYCLE_CFG_VALUE \
    (((NPU_PMU_EVENT_CYCLE    << NPU_PMU_PMCCNTR_CFG_START_SHIFT) & NPU_PMU_PMCCNTR_CFG_START_MASK) | \
     ((NPU_PMU_EVENT_NO_EVENT << NPU_PMU_PMCCNTR_CFG_STOP_SHIFT)  & NPU_PMU_PMCCNTR_CFG_STOP_MASK))

_Static_assert(NPU_PMU_EVENT_CYCLE == 17u, "unexpected CYCLE event");
_Static_assert(NPU_PMU_EVENT_NO_EVENT == 0u, "unexpected NO_EVENT");
_Static_assert(NPU_PMU_CYCLE_CFG_VALUE == 0x11u,
               "cycle counter configuration disagrees with the known encoding");
_Static_assert(NPU_PMU_CYCLE_COUNTER_WIDTH == 48, "unexpected PMU cycle width");
_Static_assert(NPU_PMU_EVENT_COUNTERS_MAX == 8, "ABI event slot count changed");
_Static_assert(NPU_PMU_PMCNTEN_CYCLE_SHIFT >= NPU_PMU_EVENT_COUNTERS_MAX,
               "PMCNTEN cycle bit overlaps the event-counter range");
_Static_assert(NPU_PMU_PMOVS_CYCLE_OVF_SHIFT >= NPU_PMU_EVENT_COUNTERS_MAX,
               "PMOVS overflow bit overlaps the event-counter range");
_Static_assert(NPU_PMU_PMCNTEN_CYCLE_SHIFT == NPU_PMU_PMOVS_CYCLE_OVF_SHIFT,
               "cycle enable and overflow bits must share a position");
/* Cross-check against the independently known encoding, exactly as
 * NPU_PMU_CYCLE_CFG_VALUE == 0x11 above. The positional rules cannot
 * catch every cycle bit being moved to the same wrong place at once:
 * bit 8 sits above the event range and the registers still agree with
 * each other. Only pinning the known value closes that. This is a
 * cross-check, NOT the source -- the value is still extracted. */
_Static_assert(NPU_PMU_PMCNTEN_CYCLE_SHIFT == 31u,
               "cycle enable bit is not at the known position 31");

#endif /* NPU_PMU_REGS_H */
