"""Canonical identity for the MLEK-generated model .cc.

The generator stamps wall-clock time into its header. This removes exactly that
one field and nothing else. It is deliberately NOT a generic "drop the first
line" rule: a future first line that is real code must not be silently excluded,
so every structural assumption is asserted and violations fail closed.

Grammar is taken from the pinned generator template, not inferred from a diff:
    scripts/py/mlek_tools/gen/templates/header_template.txt @ MLEK b2c0bb2
"""
import hashlib, re

TRANSFORM_KIND = "STRIP_MLEK_GENERATED_WALLCLOCK_METADATA"
TRANSFORM_VERSION = 1
GENERATOR_TEMPLATE = "scripts/py/mlek_tools/gen/templates/header_template.txt"
MLEK_COMMIT = "b2c0bb2884698b7328f65c41b7c8c51ca9bec386"
SCOPE = "the single ' * Date:' value inside the autogenerated header block"

BANNER = b"/*********************    Autogenerated file. DO NOT EDIT *******************\n"
HEADER_END = b" ***************************************************************************/\n"
DATE_FIELD = re.compile(rb"(\* Date:[ \t]+)(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{6})")
PLACEHOLDER = b"<CANONICALIZED>"


class CanonicalizationError(Exception):
    """Fail closed. Never fall back to hashing the raw bytes."""


def canonicalize(raw: bytes) -> bytes:
    if not isinstance(raw, bytes):
        raise CanonicalizationError("expected bytes")
    if raw.count(BANNER) != 1:
        raise CanonicalizationError("banner occurrences = %d, expected 1" % raw.count(BANNER))
    start = raw.find(BANNER)
    if raw[:start].strip(b"\r\n") != b"":
        raise CanonicalizationError("unexpected content before the autogenerated banner")
    end = raw.find(HEADER_END, start)
    if end == -1:
        raise CanonicalizationError("header terminator not found")
    end += len(HEADER_END)

    hits = list(DATE_FIELD.finditer(raw))
    if len(hits) != 1:
        raise CanonicalizationError("Date metadata occurrences = %d, expected exactly 1" % len(hits))
    m = hits[0]
    if not (start <= m.start() and m.end() <= end):
        raise CanonicalizationError("Date metadata lies outside the header block")
    # replace only the timestamp value; the label is retained
    return raw[:m.start(2)] + PLACEHOLDER + raw[m.end(2):]


def body_sha256(raw: bytes) -> str:
    return hashlib.sha256(canonicalize(raw)).hexdigest()


def transform_identity() -> dict:
    src = open(__file__, "rb").read()
    return {"kind": TRANSFORM_KIND, "version": TRANSFORM_VERSION,
            "generator_template": GENERATOR_TEMPLATE, "mlek_commit": MLEK_COMMIT,
            "scope": SCOPE,
            "transform_sha256": hashlib.sha256(src).hexdigest()}
