"""Negatives for the canonicalizer. A transform that cannot fail is not a gate."""
import sys, re
sys.path.insert(0, "/tmp/xqbin")
from ccident import canonicalize, body_sha256, CanonicalizationError, transform_identity

RAW = open(sys.argv[1], "rb").read()
base = body_sha256(RAW)
results = {}

# N1 - change ONLY the Date metadata: raw differs, body identical
n1 = re.sub(rb"(\* Date:[ \t]+)\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{6}",
            rb"\g<1>2011-11-11 11:11:11.111111", RAW, count=1)
results["N1_date_only__raw_differs"] = n1 != RAW
results["N1_date_only__body_unchanged"] = body_sha256(n1) == base

# N2 - change one byte of the model byte array
m = re.search(rb"0x[0-9a-fA-F]{2},", RAW[RAW.find(b"{"):])
off = RAW.find(b"{") + m.start() + 2
n2 = RAW[:off] + (b"0" if RAW[off:off+1] != b"0" else b"1") + RAW[off+1:]
results["N2_model_byte__body_changes"] = body_sha256(n2) != base

# N3 - change code/comment OUTSIDE the metadata field
n3 = RAW.replace(b'#include "BufAttributes.hpp"', b'#include "BufAttributes.hpp" // x', 1)
results["N3_outside_metadata__body_changes"] = n3 != RAW and body_sha256(n3) != base

# N4 - metadata missing / malformed => canonicalizer FAILS
n4 = re.sub(rb"\* Date:[ \t]+\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{6}", b"* Date:", RAW, count=1)
try:
    canonicalize(n4); results["N4_malformed_metadata__fails_closed"] = False
except CanonicalizationError:
    results["N4_malformed_metadata__fails_closed"] = True

# N5 - duplicated metadata field => FAILS
n5 = RAW.replace(b"\n#include", b"\n// * Date:            2020-01-01 00:00:00.000000\n#include", 1)
try:
    canonicalize(n5); results["N5_duplicate_metadata__fails_closed"] = False
except CanonicalizationError:
    results["N5_duplicate_metadata__fails_closed"] = True

# N6 - banner removed => FAILS (guards the "generic first-line strip" mistake)
n6 = RAW.replace(b"/*********************    Autogenerated file. DO NOT EDIT *******************\n", b"", 1)
try:
    canonicalize(n6); results["N6_no_banner__fails_closed"] = False
except CanonicalizationError:
    results["N6_no_banner__fails_closed"] = True

for k, v in results.items():
    print("  %-46s %s" % (k, "PASS" if v else "FAIL"))
print("TRANSFORM_IDENTITY:", transform_identity()["transform_sha256"][:16])
print("ALL_PASS" if all(results.values()) else "SOME_FAILED")
