import re, sys
P = "Selftest_pmu/gen_npu_pmu_regs.py"
s = open(P).read()

# Replace the whole extract/render pair with a version that reads the cycle
# bit positions out of each register's own bitfield struct.
i = s.index("def extract(path):")
j = s.index("ap = argparse.ArgumentParser()")
new = '''def _bitfields(text, struct_name):
    """Ordered (name, shift, width) for one register's C bitfield struct."""
    m = re.search(r"struct %s\\s*\\{(.+?)\\n\\};" % struct_name, text, re.S)
    if not m:
        raise SystemExit("struct %s not found" % struct_name)
    out, shift = [], 0
    for name, width in re.findall(r"uint32_t\\s+(\\w+)\\s*:\\s*(\\d+)\\s*;", m.group(1)):
        width = int(width)
        if shift >= 32:
            break
        out.append((name, shift, width))
        shift += width
    return out


def _one(fields, pattern, where):
    """Exactly one field matching `pattern`, exactly 1 bit wide, shift 0..31.

    Deliberately strict. The defect this replaces came from DERIVING the cycle
    bit from the event-counter count (8) instead of reading it: the real
    position is 31, because 8 event bits are followed by 23 reserved bits.
    Nothing here may be inferred from another register.
    """
    hits = [f for f in fields if re.fullmatch(pattern, f[0])]
    if len(hits) != 1:
        raise SystemExit("%s: expected exactly 1 field matching %s, found %d"
                         % (where, pattern, len(hits)))
    name, shift, width = hits[0]
    if width != 1:
        raise SystemExit("%s.%s: expected a 1-bit field, found %d" % (where, name, width))
    if not 0 <= shift <= 31:
        raise SystemExit("%s.%s: shift %d out of range" % (where, name, shift))
    return shift


def extract(path):
    text = open(path).read()
    found = {}
    for name in WANTED:
        hits = re.findall(r"^#define\\s+%s\\s+(0x[0-9A-Fa-f]+|\\d+)\\s*$" % name, text, re.M)
        if len(hits) != 1:
            raise SystemExit("%s: expected 1 definition, found %d" % (name, len(hits)))
        found[name] = int(hits[0], 0)

    pmcr = _bitfields(text, "pmcr_r")
    bits = {}
    for need in ("cnt_en", "event_cnt_rst", "cycle_cnt_rst", "mask_en", "num_event_cnt"):
        hit = [f for f in pmcr if f[0] == need]
        if len(hit) != 1:
            raise SystemExit("pmcr_r.%s: found %d" % (need, len(hit)))
        bits[need] = (hit[0][1], hit[0][2])

    # Cycle bits, each from its OWN register definition.
    cyc = {
        "PMCNTENSET_CYCLE": _one(_bitfields(text, "pmcntenset_r"), r"CYCLE_CNT", "pmcntenset_r"),
        "PMCNTENCLR_CYCLE": _one(_bitfields(text, "pmcntenclr_r"), r"CYCLE_CNT", "pmcntenclr_r"),
        "PMOVSSET_CYCLE_OVF": _one(_bitfields(text, "pmovsset_r"), r"CYCLE_CNT_OVF", "pmovsset_r"),
        "PMOVSCLR_CYCLE_OVF": _one(_bitfields(text, "pmovsclr_r"), r"CYCLE_CNT_OVF", "pmovsclr_r"),
    }
    if cyc["PMCNTENSET_CYCLE"] != cyc["PMCNTENCLR_CYCLE"]:
        raise SystemExit("PMCNTENSET/PMCNTENCLR cycle bit disagree: %d vs %d"
                         % (cyc["PMCNTENSET_CYCLE"], cyc["PMCNTENCLR_CYCLE"]))
    if cyc["PMOVSSET_CYCLE_OVF"] != cyc["PMOVSCLR_CYCLE_OVF"]:
        raise SystemExit("PMOVSSET/PMOVSCLR overflow bit disagree: %d vs %d"
                         % (cyc["PMOVSSET_CYCLE_OVF"], cyc["PMOVSCLR_CYCLE_OVF"]))

    cc = _bitfields(text, "pmccntr_r")
    widths = dict((n, w) for n, sh, w in cc if n.startswith("CYCLE_CNT_"))
    if widths.get("CYCLE_CNT_LO") != 32:
        raise SystemExit("CYCLE_CNT_LO width %r, expected 32" % widths.get("CYCLE_CNT_LO"))
    if widths.get("CYCLE_CNT_HI") != 16:
        raise SystemExit("CYCLE_CNT_HI width %r, expected 16" % widths.get("CYCLE_CNT_HI"))
    return found, bits, widths["CYCLE_CNT_LO"] + widths["CYCLE_CNT_HI"], cyc


def render(found, bits, cycle_width, cyc):
    L = ["/* GENERATED by Selftest_pmu/gen_npu_pmu_regs.py -- do not edit.",
         " *",
         " * Extracted from the Ethos-U core driver's register map:",
         " *   %s" % SDK_HEADER,
         " *",
         " * The driver is NOT linked; only the register geometry is borrowed,",
         " * and check mode re-verifies it against the vendor header.",
         " *",
         " * EVERY cycle-counter bit below comes from ITS OWN register struct.",
         " * Deriving one from another is what produced the milestone-1 defect:",
         " * the cycle bit was computed as 1<<8 from the event-counter count,",
         " * but 8 event bits are followed by 23 reserved bits, so the real",
         " * position is 31. Bit 8 is reserved and reads as zero, which made a",
         " * wrapped counter look overflow-free.",
         " */",
         "#ifndef NPU_PMU_REGS_H", "#define NPU_PMU_REGS_H", "",
         "/* Register offsets, relative to the NPU base (U85_BASE_ADDRESS). */"]
    for name in WANTED:
        if name.endswith("ARRLEN"):
            continue
        L.append("#define %-28s 0x%04XU" % (name, found[name]))
    L += ["",
          "#define NPU_PMU_EVENT_COUNTERS_MAX   %uU" % found["NPU_REG_PMEVCNTR_ARRLEN"],
          "#define NPU_PMU_EVENT_COUNTER_WIDTH  32U",
          "",
          "/* Cycle counter is %u bits (LO 32 + HI 16), NOT 64. */" % cycle_width,
          "#define NPU_PMU_CYCLE_COUNTER_WIDTH  %uU" % cycle_width,
          "#define NPU_PMU_CYCLE_HI_VALID_BITS  16U",
          ""]
    for fname in ("cnt_en", "event_cnt_rst", "cycle_cnt_rst", "mask_en", "num_event_cnt"):
        pos, width = bits[fname]
        L.append("#define NPU_PMCR_%s_POS %uU" % (fname.upper(), pos))
        L.append("#define NPU_PMCR_%s_MSK 0x%08XU" % (fname.upper(), ((1 << width) - 1) << pos))
    L += ["",
          "/* Per-register cycle bits. Never derived from the counter count. */",
          "#define NPU_PMU_PMCNTEN_CYCLE_SHIFT   %uU" % cyc["PMCNTENSET_CYCLE"],
          "#define NPU_PMU_PMCNTEN_CYCLE_MASK    (1U << NPU_PMU_PMCNTEN_CYCLE_SHIFT)",
          "#define NPU_PMU_PMOVS_CYCLE_OVF_SHIFT %uU" % cyc["PMOVSSET_CYCLE_OVF"],
          "#define NPU_PMU_PMOVS_CYCLE_OVF_MASK  (1U << NPU_PMU_PMOVS_CYCLE_OVF_SHIFT)",
          "",
          "_Static_assert(NPU_PMU_CYCLE_COUNTER_WIDTH == 48, \\"unexpected PMU cycle width\\");",
          "_Static_assert(NPU_PMU_EVENT_COUNTERS_MAX == 8, \\"ABI event slot count changed\\");",
          "_Static_assert(NPU_PMU_PMCNTEN_CYCLE_SHIFT != NPU_PMU_EVENT_COUNTERS_MAX,",
          "               \\"cycle bit must not coincide with the event-count-derived guess\\");",
          "", "#endif /* NPU_PMU_REGS_H */", ""]
    return "\\n".join(L)


'''
s = s[:i] + new + s[j:]
s = s.replace("found, bits, cycle_width = extract(a.header)\ntext = render(found, bits, cycle_width)",
              "found, bits, cycle_width, cyc = extract(a.header)\ntext = render(found, bits, cycle_width, cyc)")
s = s.replace('    print("  cycle counter width:           %d bits" % cycle_width)',
              '    print("  cycle counter width:           %d bits" % cycle_width)\n'
              '    print("  PMCNTEN cycle bit:             %d" % cyc["PMCNTENSET_CYCLE"])\n'
              '    print("  PMOVS  cycle overflow bit:     %d" % cyc["PMOVSSET_CYCLE_OVF"])')
open(P, "w").write(s)
print("generator rewritten")
